### ISSUE TITLE
📈 SSW Rules - LoggerMessage Templates

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.SAW.General#1]

**Comment by tomek-i** [comment]
Source: https://learn.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging

**Comment by tomek-i** [comment]
# High-Performance Logging with LoggerMessage in .NET
Logging is a critical component in modern applications, but it can introduce performance overhead, especially in high-throughput or latency-sensitive environments. The LoggerMessage class in .NET offers a solution to reduce the performance costs associated with logging. By utilizing this pattern, developers can optimize logging with fewer object allocations and reduced computational overhead.

## Key Performance Benefits of LoggerMessage
1. Reduced Object Allocations: Traditional logger extension methods often require "boxing" of value types (e.g., integers or dates) into objects. LoggerMessage avoids this by using static Action fields and strongly typed parameters, eliminating the need for boxing and reducing memory overhead.

2. Efficient Message Parsing: Logger extension methods parse the log message template each time a log entry is made. In contrast, LoggerMessage only parses the template once when the message is defined, leading to fewer computations and faster execution during logging.

3. Structured Logging: With LoggerMessage, log templates can include placeholders that are filled with specific log data, such as Item or DateTime. This makes it easier to integrate structured logging with logging frameworks like Serilog, which can enrich logs with meaningful event names.

## How to Use LoggerMessage
To use the LoggerMessage pattern, you define a static Action delegate for logging a message. The LoggerMessage.Define method is used to create these delegates with parameters such as:

- Log Level (e.g., LogLevel.Information)
- Event ID (for tracking specific events)
- Message Template (a named format string with placeholders)

For example:

```csharp
private static readonly Action<ILogger, WorkItem, Exception> s_processingPriorityItem =
    LoggerMessage.Define<WorkItem>(
        LogLevel.Information,
        new EventId(1, nameof(PriorityItemProcessed)),
        "Processing priority item: {Item}");
```

Each log message is represented as an Action delegate. This delegate is then invoked using strongly typed extension methods like PriorityItemProcessed, making it simple to log information in a structured manner with minimal performance impact.

## Logging with Scope
In addition to defining individual log messages, you can define a log scope using LoggerMessage.DefineScope. This allows you to associate a series of log entries with a specific context (e.g., the time at which an operation started). This can be helpful for tracking the lifecycle of complex operations.

Example of defining a log scope:

```csharp
private static readonly Func<ILogger, DateTime, IDisposable?> s_processingWorkScope =
    LoggerMessage.DefineScope<DateTime>("Processing scope, started at: {DateTime}");
```
You can then use this scope in your code:

```csharp
using (IDisposable? scope = logger.ProcessingWorkScope(DateTime.Now))
{
    // Perform work and log messages
}
```

## Optimizing Further with ILogger.IsEnabled
For even better performance, you can check whether logging is enabled for a particular log level using ILogger.IsEnabled(LogLevel). This check ensures that logging statements aren't called when the log level is not configured, thus avoiding unnecessary object allocations and improving efficiency.

```csharp
if (logger.IsEnabled(LogLevel.Information))
{
    logger.Information("This is a log message.");
}
```

## When to Use LoggerMessage
The LoggerMessage pattern is particularly beneficial in scenarios where logging needs to be performed frequently with minimal performance impact. It is most effective when:

- Logging is done in high-throughput scenarios (e.g., background services, real-time applications).
- You require structured logging for easier integration with advanced logging systems (e.g., Serilog, ElasticSearch).
- Reducing object allocations and computational overhead is a priority for the application.

## Conclusion
By leveraging the LoggerMessage class, developers can create high-performance logging in .NET applications with minimal overhead. This pattern reduces object allocations, improves template parsing, and makes it easier to structure logs in a way that is efficient and easy to consume. For applications where performance is critical, adopting the LoggerMessage pattern can lead to significant improvements in logging efficiency.

**Comment by tomek-i** [comment]
https://github.com/SSWConsulting/SSW.Rules.Content/pull/9541

**Comment by danielmackay** [comment]
Merged and deployed
