### ISSUE TITLE
📈 SSW Rules - Do you handle multi-OS dev teams in source control?

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.SAW.General#4]
- Git line ending config that works on both Windows and MacOS
- Include bash scripts
- Rules to better development teams
- "Do you handle multi-OS dev teams in source control"?

**Comment by tomek-i** [comment]
https://github.com/SSWConsulting/SSW.Rules.Content/pull/9566

**Comment by danielmackay** [comment]
Merged and deployed
